# Generated by Django 5.2.5 on 2025-08-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('GOOGLE', 'Google'), ('XIAOMI', 'Xiaomi'), ('HUAWEI', 'Huawei'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
