# Generated by Django 5.2.5 on 2025-08-10 22:06

from django.db import migrations


def update_brand_values(apps, schema_editor):
    """Update brand values from lowercase to uppercase"""
    Phone = apps.get_model('phones', 'Phone')

    # Mapping from old lowercase to new uppercase values
    brand_mapping = {
        'apple': 'APPLE',
        'samsung': 'SAMSUNG',
        'google': 'GOOGLE',
        'xiaomi': 'XIAOMI',
        'huawei': 'HUAWEI',
        'other': 'OTHER',
    }

    for old_brand, new_brand in brand_mapping.items():
        Phone.objects.filter(brand=old_brand).update(brand=new_brand)


def reverse_brand_values(apps, schema_editor):
    """Reverse the brand values back to lowercase"""
    Phone = apps.get_model('phones', 'Phone')

    # Mapping from uppercase back to lowercase
    brand_mapping = {
        'APPLE': 'apple',
        'SAMSUNG': 'samsung',
        'GOOGLE': 'google',
        'XIAOMI': 'xiaomi',
        'HUAWEI': 'huawei',
        'OTHER': 'other',
    }

    for old_brand, new_brand in brand_mapping.items():
        Phone.objects.filter(brand=old_brand).update(brand=new_brand)


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_update_brand_choices'),
    ]

    operations = [
        migrations.RunPython(update_brand_values, reverse_brand_values),
    ]
