# Generated by Django 5.2.5 on 2025-08-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_migrate_brand_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='credit_available',
            field=models.BooleanField(default=True, help_text='Whether this phone is available for credit purchase'),
        ),
        migrations.AddField(
            model_name='phone',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual interest rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='phone',
            name='max_installments',
            field=models.IntegerField(default=12, help_text='Maximum number of installments allowed'),
        ),
        migrations.AddField(
            model_name='phone',
            name='min_credit_score',
            field=models.IntegerField(default=600, help_text='Minimum credit score required for this phone'),
        ),
    ]
