# Generated by Django 5.2.5 on 2025-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
