# Generated by Django 5.2.3 on 2025-08-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_creditaccount_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Set to true if user's ID has been manually verified by an admin."),
        ),
    ]
