# Generated by Django 5.2.5 on 2025-08-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Save-to-Own'), ('CREDIT', 'BNPL')], default='SAVINGS', max_length=10),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='next_payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REPAYING', 'Repaying'), ('OVERDUE', 'Overdue'), ('PAID_OFF', 'Paid Off')], default='ACTIVE', max_length=10),
        ),
    ]
