# Generated by Django 5.2.5 on 2025-08-09 05:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_creditaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='installment_count',
            field=models.IntegerField(default=12, help_text='Number of installments'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('GOOGLE', 'Google'), ('ONEPLUS', 'OnePlus'), ('XIAOMI', 'Xiaomi'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='credit_available',
            field=models.BooleanField(default=True, help_text='Whether this product is available for credit purchase'),
        ),
        migrations.AddField(
            model_name='product',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual interest rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_installments',
            field=models.IntegerField(default=12, help_text='Maximum number of installments allowed'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_credit_score',
            field=models.IntegerField(default=600, help_text='Minimum credit score required for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('FEE', 'Fee'), ('LATE_FEE', 'Late Fee')], default='PAYMENT', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=0, help_text='Credit score for BNPL eligibility', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(850)]),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income for credit assessment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Save-to-Own'), ('CREDIT', 'Buy Now, Pay Later')], default='CREDIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REPAYING', 'Repaying'), ('OVERDUE', 'Overdue'), ('PAID_OFF', 'Paid Off'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_count', models.IntegerField(default=12)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_status', models.CharField(max_length=50)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
