# Generated by Django 5.2.3 on 2025-08-10 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_creditaccount_installment_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditapplication',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_application', 'Can approve credit applications'), ('can_decline_application', 'Can decline credit applications')]},
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes for internal use'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='credit_score_at_time_of_application',
            field=models.IntegerField(default=0, help_text="Applicant's credit score when application was submitted", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(850)]),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='employer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='employment_duration',
            field=models.IntegerField(blank=True, help_text='Employment duration in months', null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='requested_installment_count',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='requested_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
