# Generated by Django 5.2.3 on 2025-08-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_creditapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplication',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='installment_count',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='requested_amount',
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Applicant's monthly expenses", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Applicant's monthly income", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product'),
        ),
    ]
