# Generated by Django 5.2.5 on 2025-08-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_creditapplication_credit_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditapplication',
            options={},
        ),
    ]
