# Generated by Django 5.2.5 on 2025-08-10 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_creditapplication_options'),
        ('phones', '0003_migrate_brand_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.ForeignKey(blank=True, help_text='Link to the phone in the catalog', null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone'),
        ),
    ]
