# Generated by Django 5.2.5 on 2025-08-10 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_phone_link_to_product'),
        ('phones', '0004_phone_credit_available_phone_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplication',
            name='product',
        ),
        migrations.RemoveField(
            model_name='creditaccount',
            name='product',
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phones.phone'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phones.phone'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
