# Generated by Django 5.2.5 on 2025-08-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_link_orphaned_accounts_to_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the plan was completed', null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='is_active_plan',
            field=models.BooleanField(default=True, help_text="Whether this is the user's active plan"),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='Special pickup instructions'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='pickup_location',
            field=models.CharField(default='FlexiFone Shop, Tamale, Gumbihini', help_text='Pickup location', max_length=255),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='pickup_notified_at',
            field=models.DateTimeField(blank=True, help_text='When pickup notification was sent', null=True),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('COMPLETED', 'Plan Completed'), ('DELIVERED', 'Ready for Pickup'), ('PICKED_UP', 'Device Picked Up'), ('CLOSED', 'Closed'), ('REPAYING', 'Repaying'), ('OVERDUE', 'Overdue'), ('PAID_OFF', 'Paid Off'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
