# Generated by Django 5.2.3 on 2025-08-11 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_plan_completion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='admin_marked_by',
            field=models.ForeignKey(blank=True, help_text='Admin who marked device ready', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='admin_marked_ready_at',
            field=models.DateTimeField(blank=True, help_text='When admin marked device ready for pickup', null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When email notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='pickup_confirmation_method',
            field=models.CharField(blank=True, help_text='How pickup was confirmed: dashboard, phone, in_person', max_length=50),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='When SMS notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='user_confirmed_pickup_at',
            field=models.DateTimeField(blank=True, help_text='When user confirmed device pickup', null=True),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('COMPLETED', 'Plan Completed'), ('AVAILABLE_FOR_PICKUP', 'Available for Pickup'), ('PICKED_UP', 'Device Picked Up'), ('CLOSED', 'Plan Closed'), ('REPAYING', 'Repaying'), ('OVERDUE', 'Overdue'), ('PAID_OFF', 'Paid Off'), ('DECLINED', 'Declined')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=25),
        ),
    ]
