# Generated by Django 5.2.3 on 2025-08-12 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_enhanced_plan_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='payment_allowed',
            field=models.BooleanField(default=False, help_text='Whether user can proceed with payments'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes during verification'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the application was verified', null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('VERIFIED', 'Verified for Payment')], default='PENDING', max_length=25),
        ),
    ]
