# Generated by Django 5.2.3 on 2025-08-18 14:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_address_line_1_user_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Current credit limit in GHS', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_tier',
            field=models.CharField(choices=[('STARTER', 'Starter (₵500-1000)'), ('BRONZE', 'Bronze (₵1000-2500)'), ('SILVER', 'Silver (₵2500-5000)'), ('GOLD', 'Gold (₵5000-10000)'), ('PLATINUM', 'Platinum (₵10000+)')], default='STARTER', help_text='Current credit tier in FlexiFone system', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='internal_credit_score',
            field=models.IntegerField(default=100, help_text='Internal FlexiFone credit score (0-1000)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='user',
            name='last_credit_review',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last time credit tier was reviewed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='missed_payments',
            field=models.IntegerField(default=0, help_text='Number of missed payments'),
        ),
        migrations.AddField(
            model_name='user',
            name='successful_payments',
            field=models.IntegerField(default=0, help_text='Number of successful payments made'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_credit_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total credit amount used historically', max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=0, help_text='External credit score for reference', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(850)]),
        ),
    ]
