# Generated by Django 5.2.3 on 2025-08-20 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_credit_limit_user_credit_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='guarantor_national_id',
            field=models.CharField(blank=True, help_text='National ID of the guarantor provided during application', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='guarantor_username',
            field=models.CharField(blank=True, help_text='Username of the guarantor provided during application', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='guarantor_validated',
            field=models.BooleanField(default=False, help_text='Whether the guarantor information has been validated'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='guarantor_validation_notes',
            field=models.TextField(blank=True, help_text='Notes from guarantor validation process'),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_national_id',
            field=models.CharField(blank=True, help_text='National ID of the guarantor', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_username',
            field=models.CharField(blank=True, help_text='Username of the guarantor (must be a verified FlexiFone user)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_verified',
            field=models.BooleanField(default=False, help_text='Whether the guarantor information has been verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the guarantor was verified', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guarantor_verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified the guarantor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guarantees', to=settings.AUTH_USER_MODEL),
        ),
    ]
